apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-bgasnnis
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-bgasnnis:7f1064504dbe508de89da40280dc075232529a66@sha256:d9cca24ce573332cd5f34a94ff6ac8057d409466ab212b02208e25677c336b65
          name: container-image
